// Code generated by MockGen. DO NOT EDIT.
// Source: internal/validation/task_validator.go

// Package validation is a generated GoMock package.
package mocks

import (
	models "TaskProcessingService/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockITaskValidator is a mock of ITaskValidator interface.
type MockITaskValidator struct {
	ctrl     *gomock.Controller
	recorder *MockITaskValidatorMockRecorder
}

// MockITaskValidatorMockRecorder is the mock recorder for MockITaskValidator.
type MockITaskValidatorMockRecorder struct {
	mock *MockITaskValidator
}

// NewMockITaskValidator creates a new mock instance.
func NewMockITaskValidator(ctrl *gomock.Controller) *MockITaskValidator {
	mock := &MockITaskValidator{ctrl: ctrl}
	mock.recorder = &MockITaskValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITaskValidator) EXPECT() *MockITaskValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockITaskValidator) Validate(tasks models.Tasks) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", tasks)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockITaskValidatorMockRecorder) Validate(tasks interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockITaskValidator)(nil).Validate), tasks)
}
